name: frontend
description: "Kolejna podroz frontend"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  http: ^0.13.4
  equatable: ^2.0.3
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9
  

flutter:
  uses-material-design: true
  assets:
    - lib/assets/photos/
