// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6vOfOlTAtCXg5SnAbTf0TGHtY0SnYU-c',
    appId: '1:407886094574:web:47176b6d607176f8db53ff',
    messagingSenderId: '407886094574',
    projectId: 'kolejna-podroz',
    authDomain: 'kolejna-podroz.firebaseapp.com',
    storageBucket: 'kolejna-podroz.appspot.com',
    measurementId: 'G-7G979NJERD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjLAe_c07AvvMdxHwsPGtQvP4xgI0N_Os',
    appId: '1:407886094574:android:87f18fb2c1655e14db53ff',
    messagingSenderId: '407886094574',
    projectId: 'kolejna-podroz',
    storageBucket: 'kolejna-podroz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD09ieh9wjwtYAXdgPJ2mfTil7RmL0rww',
    appId: '1:407886094574:ios:649fce10fa2b00e7db53ff',
    messagingSenderId: '407886094574',
    projectId: 'kolejna-podroz',
    storageBucket: 'kolejna-podroz.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD09ieh9wjwtYAXdgPJ2mfTil7RmL0rww',
    appId: '1:407886094574:ios:649fce10fa2b00e7db53ff',
    messagingSenderId: '407886094574',
    projectId: 'kolejna-podroz',
    storageBucket: 'kolejna-podroz.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6vOfOlTAtCXg5SnAbTf0TGHtY0SnYU-c',
    appId: '1:407886094574:web:82feec127768ed19db53ff',
    messagingSenderId: '407886094574',
    projectId: 'kolejna-podroz',
    authDomain: 'kolejna-podroz.firebaseapp.com',
    storageBucket: 'kolejna-podroz.appspot.com',
    measurementId: 'G-9TNVN22MBF',
  );
}
