// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCldZAIlZf7ofhvOOZ1pNGFBSrDeALw7Vc',
    appId: '1:337971858887:web:56379f453f23614b175de2',
    messagingSenderId: '337971858887',
    projectId: 'kolejnapodroz-ed096',
    authDomain: 'kolejnapodroz-ed096.firebaseapp.com',
    storageBucket: 'kolejnapodroz-ed096.appspot.com',
    measurementId: 'G-Y278RTX31X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlZyPNYQWlYeyy7SDJ18GnhHmjIsxdphI',
    appId: '1:337971858887:android:ce03933d1020d2b1175de2',
    messagingSenderId: '337971858887',
    projectId: 'kolejnapodroz-ed096',
    storageBucket: 'kolejnapodroz-ed096.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA57rJQ12BCR1XHMwYCnHClcjIfg6fobcY',
    appId: '1:337971858887:ios:166f5711889636c3175de2',
    messagingSenderId: '337971858887',
    projectId: 'kolejnapodroz-ed096',
    storageBucket: 'kolejnapodroz-ed096.appspot.com',
    iosClientId: '337971858887-8qbocvs727ggjhgo26vfffpebp94nig1.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA57rJQ12BCR1XHMwYCnHClcjIfg6fobcY',
    appId: '1:337971858887:ios:166f5711889636c3175de2',
    messagingSenderId: '337971858887',
    projectId: 'kolejnapodroz-ed096',
    storageBucket: 'kolejnapodroz-ed096.appspot.com',
    iosClientId: '337971858887-8qbocvs727ggjhgo26vfffpebp94nig1.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCldZAIlZf7ofhvOOZ1pNGFBSrDeALw7Vc',
    appId: '1:337971858887:web:c8df03fcc5e86f9f175de2',
    messagingSenderId: '337971858887',
    projectId: 'kolejnapodroz-ed096',
    authDomain: 'kolejnapodroz-ed096.firebaseapp.com',
    storageBucket: 'kolejnapodroz-ed096.appspot.com',
    measurementId: 'G-32KE36GLVT',
  );
}
