name: Test and Deploy Frontend App

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get
        working-directory: frontend

      - name: Generate mocks
        run: flutter pub run build_runner build --delete-conflicting-outputs
        working-directory: frontend

      - name: Run tests
        run: flutter test test/_register_page_test.dart
        working-directory: frontend

      - name: Build Flutter app
        run: flutter build web --release
        working-directory: frontend
